apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: final-project-auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 84
          env:
            - name: PORT
              value: "84"
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: NODE_ENV
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: JWT_SECRET
            - name: JWT_EXPIRE
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: JWT_EXPIRE
            - name: JWT_COOKIE_EXPIRE
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: JWT_COOKIE_EXPIRE
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_REGION
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: HOST
            - name: S3_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: S3_BUCKET_NAME
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_SECRET_ACCESS_KEY
            - name: EMAIL_SERVICE_URL
              value: "http://mail-service.my-app.svc.cluster.local"

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: LoadBalancer
  selector:
    app: auth-service
  ports:
    - port: 84
      targetPort: 84

