apiVersion: apps/v1
kind: Deployment
metadata:
  name: campground-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: campground-service
  template:
    metadata:
      labels:
        app: campground-service
    spec:
      containers:
        - name: campground-service
          image: docker.io/tenkr/campground-service-image:lastest
          ports:
            - containerPort: 81
          env:
            - name: PORT
              value: "81"
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: NODE_ENV
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: JWT_SECRET
            - name: JWT_EXPIRE
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: JWT_EXPIRE
            - name: JWT_COOKIE_EXPIRE
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: JWT_COOKIE_EXPIRE
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_REGION
            - name: HOST
              value: "http://campground-service.default.svc.cluster.local"
            - name: S3_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: S3_BUCKET_NAME
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_SECRET_ACCESS_KEY
            - name: AUTH_SERVICE_URL
              value: "http://auth-service.default.svc.cluster.local:84/api/v1/auth"

---

apiVersion: v1
kind: Service
metadata:
  name: campground-service
spec:
  type: LoadBalancer
  selector:
    app: campground-service
  ports:
    - port: 81
      targetPort: 81


