apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
      containers:
        - name: auth-service
          image: docker.io/tenkr/auth-service-image:lastest
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NODE_ENV
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_EXPIRE
            - name: JWT_COOKIE_EXPIRE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_COOKIE_EXPIRE
            - name: HOST
              value: "http://auth-service.my-app.svc.cluster.local"
            - name: EMAIL_SERVICE_URL
              value: "http://mail-service.my-app.svc.cluster.local:83/api/v1"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: campground-service
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campground-service
  template:
    metadata:
      labels:
        app: campground-service
    spec:
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
      containers:
        - name: campground-service
          image: docker.io/tenkr/campground-service-image:lastest
          ports:
            - containerPort: 81
          env:
            - name: PORT
              value: "81"
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NODE_ENV
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: AUTH_SERVICE_URL
              value: "http://auth-service.my-app.svc.cluster.local/api/v1/auth"
            - name: HOST
              value: "http://campground-service.my-app.svc.cluster.local"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-chat-service
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-chat-service
  template:
    metadata:
      labels:
        app: llm-chat-service
    spec:
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
      containers:
        - name: llm-chat-service
          image: docker.io/tenkr/llm-chat-service-image:lastest
          ports:
            - containerPort: 82
          env:
            - name: PORT
              value: "82"
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NODE_ENV
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: AUTH_SERVICE_URL
              value: "http://auth-service.my-app.svc.cluster.local/api/v1/auth"
            - name: HOST
              value: "http://llm-chat-service.my-app.svc.cluster.local"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-service
  template:
    metadata:
      labels:
        app: mail-service
    spec:
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
      containers:
        - name: mail-service
          image: docker.io/tenkr/mail-service-image:v2
          ports:
            - containerPort: 83
          env:
            - name: PORT
              value: "83"
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NODE_ENV
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: AUTH_EMAIL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AUTH_EMAIL
            - name: AUTH_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AUTH_PASS
            - name: AUTH_SERVICE_URL
              value: "http://auth-service.my-app.svc.cluster.local/api/v1/auth"
            - name: HOST
              value: "http://mail-service.my-app.svc.cluster.local"
