apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: multi-service-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80  # Match the service port (auth-service is exposed on port 80)
          - path: /campground
            pathType: Prefix
            backend:
              service:
                name: campground-service
                port:
                  number: 80  # Match the service port (campground-service is exposed on port 80)
          - path: /chat
            pathType: Prefix
            backend:
              service:
                name: llm-chat-service
                port:
                  number: 80  # Match the service port (llm-chat-service is exposed on port 80)
          - path: /mail
            pathType: Prefix
            backend:
              service:
                name: mail-service
                port:
                  number: 80  # Match the service port (mail-service is exposed on port 80)
