apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-service
  template:
    metadata:
      labels:
        app: mail-service
    spec:
      containers:
        - name: mail-service
          image: final-project-mail-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 83
          env:
            - name: PORT
              value: "83"
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: NODE_ENV
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: JWT_SECRET
            - name: JWT_EXPIRE
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: JWT_EXPIRE
            - name: JWT_COOKIE_EXPIRE
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: JWT_COOKIE_EXPIRE
            - name: HOST
              value: "http://mail-service.default.svc.cluster.local"
            - name: AUTH_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AUTH_EMAIL
            - name: AUTH_PASS
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AUTH_PASS
            - name: AUTH_SERVICE_URL
              value: "http://auth-service.default.svc.cluster.local:84/api/v1/auth"

---

apiVersion: v1
kind: Service
metadata:
  name: mail-service
spec:
  type: LoadBalancer
  selector:
    app: mail-service
  ports:
    - port: 83
      targetPort: 83



